### ISSUE TITLE
fcitx-aggressive-setup will cause emacs frozen.

### ISSUE THREAD

**Issue by zilongshanren** [cute-jumper/fcitx.el#8] opened 2015-11-05 13:06 UTC
see https://github.com/justbur/emacs-which-key/issues/81

**Comment by cute-jumper** [comment] 2015-11-05 18:10
It's weird. I also used `which-key-mode` and `fcitx-aggressive-setup`, and I just tested with the latest `fcitx.el`. I can't reproduce your problem. Can you give more details?

**Comment by zilongshanren** [comment] 2015-11-06 01:09
@cute-jumper 

Maybe it's related to my own configs, I have a defadvice which will turn `evil-insert-state` to `evil-emacs-state` automatically.  And here it will call fcitx related functions to toggle input method.

But I think `fcitx-aggresisve-setup` also does this. 

I will try your solution by disabling the `evil-insert-map` and see whether this issue is still exists or not.

**Comment by zilongshanren** [comment] 2015-11-06 01:14
@cute-jumper 
This issue is still exists..

wired..

**Comment by cute-jumper** [comment] 2015-11-06 01:33
I try a clean startup with `emacs -Q` and then turn on `which-key-mode` and `fcitx-aggressive-setup`, it works well, too. So it must be some settings or some other packages that make `fcitx.el` unable to work.

Can you give me your `which-key` settings?

**Comment by zilongshanren** [comment] 2015-11-09 03:42
@cute-jumper 
I don't do any configuration over the default spacemacs which-key settings.
So you could use Spacemacs as a test environment.

**Comment by cute-jumper** [comment] 2015-11-09 04:20
Here is what I've done:
1. Git clone Spacemacs repo.
2. Start Emacs and Spacemacs will install all the packages.
3. Restart Emacs. `M-x package install RET fcitx`.
4. Call `fcitx-aggressive-setup`, and enable fcitx now.
5. Type `C-x`, fcitx is temporarily disabled and `whick-key` shows a popup windows. Still, no hanging problem has been found.

Can you give me steps so that I can reproduce your problem?

**Comment by zilongshanren** [comment] 2015-11-09 05:37
@cute-jumper 
Maybe the bug is  inside my own spacemacs configs. I can't  dig into it at the moment.

**Comment by cute-jumper** [comment] 2015-11-09 06:31
I can't help if I have no information of your environment. In case you use [fcitx-remote-for-osx](https://github.com/CodeFalling/fcitx-remote-for-osx), maybe issue #5 could help. I'm closing this issue. Feel free to reopen it when you have time to investigate the issue.

**Closed by cute-jumper** 2015-11-09 06:31 UTC

**Comment by zilongshanren** [comment] 2015-11-09 06:41
@cute-jumper 
Thanks, I will keep a eye on it.

**Comment by CodeFalling** [comment] 2016-02-09 14:56
Maybe it's not cause by neither `fcitx-remote-for-osx` or `which-key`. See #13.
