### ISSUE TITLE
fcitx-aggressive-setup hangs emacs when `fcitx` not started

### ISSUE THREAD

**Issue by CodeFalling** [cute-jumper/fcitx.el#13] opened 2016-02-09 14:56 UTC
## Env
```
- Emacs version: `GNU Emacs 25.0.50.2`
- Arch Linux
- fcitx version: `4.2.9.1`
```

## Step to reproduce
- run `emacs -q` under `fish shell`
- eval
```
(package-initialize)
(require 'fcitx)
(fcitx-aggressive-setup)
```
- `C-x C-f`

Then emacs got hanged.

## Issues related
#8 #5

**Comment by cute-jumper** [comment] 2016-02-09 20:07
No. I can't reproduce it. My emacs version is `25.1.50.1`, which is the latest build from master. The only difference is that I ran `fish` inside `zsh` instead of running fish as the login shell. Can you look at the backtrace(`toggle-debug-on-quit`) to find out where emacs hangs?

**Comment by CodeFalling** [comment] 2016-02-10 02:54
However I set `zsh` as default shell then ran `fish` inside.Steps above still reproduce.

This is backtrace

```
Debugger entered--Lisp error: (quit)
  call-process("fcitx-remote" nil t)
  fcitx--active-p-proc()
  fcitx--active-p()
  fcitx--prefix-keys-maybe-deactivate()
  fcitx--prefix-keys-polling-function()
  apply(fcitx--prefix-keys-polling-function nil)
  timer-event-handler([t 22202 1038 284558 0.1 fcitx--prefix-keys-polling-function nil nil 806125])
```

**Comment by cute-jumper** [comment] 2016-02-10 03:01
From the backtrace, it is `call-process` that hangs emacs. Can you just try to use `call-process` to invoke some shell commands, including `fcitx-remote`, to see what's wrong with `call-process`. For a quick and temporary workaround(since you're using Linux), you can set `fcitx-use-dbus`:

    (setq fcitx-use-dbus t)

which will avoid the call of `call-process` function.

**Comment by CodeFalling** [comment] 2016-02-10 03:14
It's not `call-process` hangs emacs.`(fcitx--check-status)` just got `nil` even input method is toggle on.

**Comment by CodeFalling** [comment] 2016-02-10 03:28
Sorry for wrong report.It not about `fish`.
**I just forget to ran `fcitx` before**.But it's not `call-process` hang emacs.I eval `(fcitx--deactivate-proc)` by hand and everything is ok.But `C-xC-f` got hanged.

**Comment by cute-jumper** [comment] 2016-02-10 03:42
What do you mean by "forgot to run fcitx before"? So is it solved now, or `C-x C-f` still hangs?

**Comment by CodeFalling** [comment] 2016-02-10 03:44
Run emacs without `fcitx`(`pkill fcitx`),then `C-x C-f` still hangs.

With `fcitx` it works well.

**Comment by cute-jumper** [comment] 2016-02-10 04:44
Thanks for reporting. I see. The setup function now will check whether `fcitx` is running. If not, it will give a warning and all the functions will not be turned on. See commit https://github.com/cute-jumper/fcitx.el/commit/5056cef0dd1ae3253f2723b5b3ba0d7361bc9d21. However, `fcitx.el` will not take care of running `fcitx`. You need to run it yourself.

**Comment by CodeFalling** [comment] 2016-02-10 08:03
Thx.But why it hangs emacs?I don't know whether it really related to #5 #8.Because `fcitx-remote-for-osx` would never return `0`(which `fcitx-remote` return when `fcitx` not running)

**Comment by cute-jumper** [comment] 2016-02-10 08:20
The reason is that it will call `call-process` every `fcitx-prefix-keys-polling-time`, which is 0.1s. It tries to deactivate `fcitx`, but never succeeds. And although the doc says `fcitx-remote` will display 0 for close, it will actually print "Not get reply".

**Comment by cute-jumper** [comment] 2016-02-17 01:01
I'm closing this issue now. If you experience the same problem again, feel free to reopen it. Thanks!

**Closed by cute-jumper** 2016-02-17 01:01 UTC
